# Generated by Django 4.2.24 on 2025-11-21 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_remove_purchaseorder_supplier'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
