# Generated by Django 4.2.24 on 2025-10-01 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'warehouse',
            },
        ),
        migrations.CreateModel(
            name='StockMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_type', models.CharField(choices=[('SALE', 'Sale'), ('GRN', 'Goods Receipt'), ('ADJUST', 'Adjustment'), ('TRANSFER', 'Transfer')], max_length=20)),
                ('ref_id', models.BigIntegerField(blank=True, null=True)),
                ('qty_in', models.IntegerField(default=0)),
                ('qty_out', models.IntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('moved_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse')),
            ],
            options={
                'db_table': 'stock_move',
                'indexes': [models.Index(fields=['ref_type', 'ref_id'], name='idx_sm_ref'), models.Index(fields=['product', 'moved_at'], name='idx_sm_product_date')],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse')),
            ],
            options={
                'db_table': 'stock',
                'unique_together': {('product', 'warehouse')},
            },
        ),
        migrations.CreateModel(
            name='ReorderPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_daily_demand', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lead_time_days', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('service_level', models.DecimalField(decimal_places=2, default=95.0, max_digits=5)),
                ('demand_std', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rop', models.IntegerField(default=0)),
                ('safety_stock', models.IntegerField(default=0)),
                ('reorder_qty', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse')),
            ],
            options={
                'db_table': 'reorder_policy',
                'unique_together': {('product', 'warehouse')},
            },
        ),
    ]
