# Generated by Django 4.2.24 on 2025-10-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antecedent', models.JSONField()),
                ('consequent', models.JSONField()),
                ('support', models.DecimalField(decimal_places=4, max_digits=6)),
                ('confidence', models.DecimalField(decimal_places=4, max_digits=6)),
                ('lift', models.DecimalField(decimal_places=4, max_digits=8)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'association_rule',
                'indexes': [models.Index(fields=['lift', 'confidence', 'support'], name='idx_rule_metrics')],
            },
        ),
    ]
